label_map:
  0: "unlabeled"
  1: "person"
  2: "bicycle"
  3: "car"
  4: "motorcycle"
  6: "bus"
  7: "train"
  8: "truck"
  10: "traffic"
  12: "street"
  13: "stop"
  14: "parking"
  17: "cat"
  18: "dog"
  19: "horse"
  20: "sheep"
  21: "cow"
  22: "elephant"
  23: "bear"
  24: "zebra"
  25: "giraffe"
