# raw label coco map can be found here:
# https://gist.githubusercontent.com/iitzco/3b2ee634a12f154be6e840308abfcab5/raw/89d26e0aa56b0c356fb78cc2408fc64f4197b88a/coco_label_map.py
label_map:
  1: "person"
  2: "bicycle"
  3: "car"
  4: "motorcycle"
  6: "bus"
  8: "truck"